# Generated by Django 4.1.3 on 2022-12-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_album_num_starts'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
    ]
