# Generated by Django 4.1.3 on 2022-12-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_alter_album_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='Musician',
        ),
    ]
