# Generated by Django 4.1.3 on 2022-12-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
